### ISSUE TITLE
Parameterized generics cannot be used with class or instance checks

### ISSUE THREAD

**Issue by hammansamuel** [JonathanMurray/matchmaker#1]
Full trace of the error message is below when I ran `python main.py` (I'm running Python 3.6.5 Anaconda)

```
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    run_demo()
  File "main.py", line 22, in run_demo
    demo.run(mm, mmr_engine, env, skip_rounds=60)
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\demo.py", line 51, in run
    self._main_loop(skip_rounds)
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\demo.py", line 56, in _main_loop
    self.engine.one_round()
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\engine.py", line 63, in one_round
    self._find_lobbies_and_start_games()
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\engine.py", line 70, in _find_lobbies_and_start_games
    self._match_maker.find_lobbies(self._queue, self._on_found_lobby)
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\matchmakers.py", line 20, in find_lobbies
    found_lobby_callback(t1, t2)
  File "C:\Users\hsamuel\Downloads\matchmaker-master\core\engine.py", line 106, in _on_found_lobby
    if not (isinstance(team_1, List[Queuer]) and isinstance(team_2, List[Queuer])):
  File "C:\Users\hsamuel\AppData\Local\Continuum\anaconda2\envs\py36\lib\typing.py", line 1162, in __instancecheck__
    return issubclass(instance.__class__, self)
  File "C:\Users\hsamuel\AppData\Local\Continuum\anaconda2\envs\py36\lib\typing.py", line 1148, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks
```

**Comment by JonathanMurray** [comment]
It seems to be a problem with the `typing` library that happens on some Python versions.
https://github.com/python/typing/issues/477

Python 3.5.2 works for me. I was able to reproduce the error on an older Python version.
